name: Docker Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t my-node-app:latest .
      - name: Save Docker image to tar #because a Docker image lives inside the Docker daemon (not as a regular file) — you must export it to a file (e.g., with docker save) to upload as an artifact.
        run: |
          docker save -o image.tar my-node-app:latest
      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar

